### ISSUE TITLE
Docker Hub images

### ISSUE THREAD

**Issue by odubuc** [ricardobranco777/regview#2]
[Docker Hub](https://hub.docker.com/r/ricardobranco/regview) image gone ? 

![image](https://github.com/ricardobranco777/regview/assets/1559169/07903543-3ff4-4cef-a3aa-125cdbb2abfb)

**Comment by ricardobranco777** [comment]
Yes. The image wasn't updated anyway as I'm not happy with the path that Docker Hub took rate-limiting pulls, so I decided to remove my account.

I will use the Github Container Registry for that using Github Actions.

**Comment by ricardobranco777** [comment]
Fixed by https://github.com/ricardobranco777/regview/pull/3
